services:
  webapi:
    build:
      context: ./DotNetProject10
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7185
    ports:
      - "7185:7185"
    depends_on:
      - sqlserver
      - mongodb

  frontend:
    build:
      context: ./Frontend
    depends_on:
      - webapi
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - BACKEND_URL=http://webapi:7185
    ports:
      - "8080:8080"

  sqlserver:
    build:
      context: ./db/sqlserver
    environment:
      - MSSQL_SA_PASSWORD=Test_Password1!
      - ACCEPT_EULA=Y
    ports:
      - "1400:1433"
    volumes:
      - sqldata:/var/opt/mssql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  mongodb:
    build:
      context: ./db/mongodb
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=Test_Password1!
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  sqldata:
  mongodata:
